### ISSUE TITLE
when i install this repository return 404

### ISSUE THREAD

**Issue by chunmu** [Lichwa/react-native-file-picker#1]

**Comment by AppDev666** [comment]
@chunmu run 
npm install https://github.com/Lichwa/react-native-file-picker --save

**Comment by chunmu** [comment]
i will try tomorrow or other day

**Comment by hepu-appmeup** [comment]
The package is not on NPM

**Comment by chunmu** [comment]
yeap    maybe has been removed

**Comment by chunmu** [comment]
@hepu-appmeup   npm install https://github.com/Lichwa/react-native-file-picker --save AppDev666 said

**Comment by luisfuertes** [comment]
Or install my PR  npm install https://github.com/luisfuertes/react-native-file-picker --save

**Comment by Lichwa** [comment]
Yes, just install fork from @luisfuertes. I didn't use or update this repo in almost a year and didn't even realize someone was using it.

**Comment by luisfuertes** [comment]
Ok, i publish it on npm, now `npm install react-native-file-picker@latest --save` install my repository. Close issue if you want and thansk fors answer @Lichwa
